#!/usr/bin/env bash
# One-shot: apply Terraform, then write apps/api/.env.deploy.generated from outputs (+ Bedrock model hints).
# Prerequisites: aws CLI, terraform, postgres reachable if you run API locally against RDS.
#
# Usage:
#   ./scripts/deploy-stack.sh                    # terraform apply (interactive) + write env file
#   AUTO_APPROVE=1 ./scripts/deploy-stack.sh   # terraform apply -auto-approve
#   DEPLOY_TFVARS=infra/terraform/terraform.tfvars ./scripts/deploy-stack.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="${TERRAFORM_DIR:-$ROOT/infra/terraform}"
OUT_FILE="${DEPLOY_ENV_OUT:-$ROOT/apps/api/.env.deploy.generated}"

EXTRA_TF=()
if [[ -n "${DEPLOY_TFVARS:-}" ]]; then
  EXTRA_TF=( -var-file="${DEPLOY_TFVARS}" )
fi

APPLY_FLAGS=()
if [[ "${AUTO_APPROVE:-}" == "1" ]]; then
  APPLY_FLAGS=( -auto-approve )
fi

echo "==> Terraform apply (${TF_DIR})"
# Bash + `set -u`: empty-array expansion of EXTRA_TF/APPLY_FLAGS errors unless guarded.
terraform -chdir="$TF_DIR" apply "${EXTRA_TF[@]+"${EXTRA_TF[@]}"}" "${APPLY_FLAGS[@]+"${APPLY_FLAGS[@]}"}"

REGION="$(terraform -chdir="$TF_DIR" output -raw region)"
DB_URL="$(terraform -chdir="$TF_DIR" output -raw database_url)"
REDIS_URL="$(terraform -chdir="$TF_DIR" output -raw redis_url)"
S3_BUCKET="$(terraform -chdir="$TF_DIR" output -raw s3_bucket)"
PUBLIC_WEB_URL="$(terraform -chdir="$TF_DIR" output -raw public_web_url)"
PUBLIC_API_URL="$(terraform -chdir="$TF_DIR" output -raw public_api_url)"

# Defaults: Google Gemma 3 (translate) + OpenAI GPT-OSS on Bedrock (judge). Override before running if needed.
BEDROCK_TRANSLATION_MODEL_ID="${BEDROCK_TRANSLATION_MODEL_ID:-google.gemma-3-12b-it}"
BEDROCK_SCORING_MODEL_ID="${BEDROCK_SCORING_MODEL_ID:-openai.gpt-oss-120b-1:0}"

cat >"$OUT_FILE" <<EOF
# Generated by scripts/deploy-stack.sh — merge into apps/api/.env (do not commit secrets).
PORT=3001
AWS_REGION=$REGION
DATABASE_URL=$DB_URL
REDIS_URL=$REDIS_URL
S3_REGION=$REGION
S3_BUCKET=$S3_BUCKET
# Real S3: omit endpoint / force path style
S3_ENDPOINT=
S3_FORCE_PATH_STYLE=false

BEDROCK_TRANSLATION_MODEL_ID=$BEDROCK_TRANSLATION_MODEL_ID
BEDROCK_SCORING_MODEL_ID=$BEDROCK_SCORING_MODEL_ID

# --- Public URLs (terraform output; ECS tasks must have images pushed first) ---
# Web UI (Next.js ALB): $PUBLIC_WEB_URL
# REST API (Nest ALB):  $PUBLIC_API_URL
EOF

chmod 600 "$OUT_FILE" 2>/dev/null || true

echo ""
echo "Wrote $OUT_FILE"
echo "Public Web UI: $PUBLIC_WEB_URL"
echo "Public API:    $PUBLIC_API_URL"
echo ""
echo "Push Docker images and roll ECS:"
echo "  ./scripts/push-ecr-aws.sh"
echo "Migrate + seed RDS (one-off task or bastion):"
echo "  DATABASE_URL='<from terraform output database_url>' pnpm --filter api exec prisma db push"
echo "  DATABASE_URL='...' pnpm --filter api run db:seed"
